# 🏭 ACP Coating Manufacturer — Executive Analysis Notebook

**Purpose:** Step-by-step analytical walkthrough of all three dashboard requirements:

1. **Material Requirements** — Project base material needs for open orders, including net-to-order quantities and recommended purchase dates (Ship Date − 14 days)
2. **Scrap Cost Analysis** — Calculate scrap cost from historical orders and the open order using multi-level BOM roll-up
3. **Customer Ordering Trends** — Analyse whether customers are ordering more or less frequently and whether per-unit volume is growing or shrinking

---
**Data Source:** `Items_Whitby_Extract.xlsx`  
**Products:** T040111 (WTB Release Paper 109" 40/15) · T018074 (KROGER 2HR 14×16 bag)  
**⚠️ Key Note — T018074:** BOMs roll up through **4 levels** of semi-finished goods before reaching base materials (Paper + Film). All scrap % compounds through each level.  
**💡 Key Note — T040111:** The product itself appears in the **Inventory Extract**, meaning finished goods stock can partially or fully satisfy the open order before any manufacturing is required. The analysis automatically nets the order quantity against on-hand finished goods (`net_to_manufacture = max(order_qty − on_hand, 0)`).

---

In [34]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

from utils import (
    load_all_data,
    roll_up_material,
    build_material_requirements,
    build_historical_scrap_table,
    analyse_ordering_trend,
    project_next_order_date,
)

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.4f}'.format)
print('✅ Libraries loaded')

✅ Libraries loaded

## 📂 Step 1 — Load & Inspect All Data

In [35]:
df_inv, customer_data = load_all_data()

# Build combined BOM dict so T018074's 4-level chain resolves across sheets
all_boms = {}
for cdata in customer_data.values():
    all_boms.update(cdata['boms'])
for order_no in customer_data:
    customer_data[order_no]['boms'] = all_boms

inv_lookup = df_inv.set_index('No.').to_dict('index')

print(f"Inventory rows  : {len(df_inv)}")
print(f"Customer orders : {list(customer_data.keys())}")
print(f"Total BOM items : {len(all_boms)}")
print("\n=== INVENTORY (first 10 rows) ===")
display(df_inv.head(10))

Inventory rows  : 56
Customer orders : ['T040111', 'T018074']
Total BOM items : 5

=== INVENTORY (first 10 rows) ===

,No.,Quantity on Hand,<No Of Rolls>,Description,Item Category Code,Product Group Code,Base Unit of Measure,Total,Unit Cost
0,C1S 25 40.75,847.0000,1,"25LB C1S WHT 40.75""",BASE MATRL,PAPER,LBS,"1,160.0173",2.7391
1,C1S 55 48.75,"15,000.0000",6,"55LB C1S POINTFLEX 48.75""",BASE MATRL,PAPER,LBS,"17,060.5500",2.2747
2,C1S 55 49.95,"38,100.0000",15,55LB C1S POINTFLEX 49.95”,BASE MATRL,PAPER,LBS,"43,312.0800",2.2736
3,FILM 1.15 45,"2,668.0000",2,"FILM 1.15 HD 45""",BASE MATRL,FL/SCR/FM,LBS,"6,269.8000",4.7000
4,FILM 1.15 49.25,"1,596.0000",1,"FILM 1.15 HD 49.25""",BASE MATRL,NaN,LBS,"6,269.8000",1.5800
5,FILM 1.15 60.5,"8,322.0000",4,"FILM 1.15 HD 60.5""",BASE MATRL,FL/SCR/FM,LBS,"19,223.8200",4.6200
6,FILM 2.5 LLDPE 54.5,100.0000,1,FILM 2.5 LLDPE 54.5 CGL1,BASE MATRL,FL/SCR/FM,LBS,189.0000,3.7800
7,FILM 48G PET 37,627.0000,1,"48G PET CLR 37""",BASE MATRL,FL/SCR/FM,LBS,"1,269.4305",4.0492
8,FILM CPP 1 MIL 49.75,254.0000,1,FILM CPP HP204 1S TREATED,BASE MATRL,FL/SCR/FM,LBS,838.7105,6.6040
9,FILM MET PET 53,882.0000,1,"CEL-MET PET 48G 53""",BASE MATRL,FL/SCR/FM,LBS,"2,403.4500",5.4500

In [36]:
# Key base materials referenced in BOM roll-ups
key_mats = ['K 40 M/W 112.5', 'K BLCH 30 49.5', 'FILM 1.15 49.25']
print("=== KEY BASE MATERIALS ===")
display(df_inv[df_inv['No.'].isin(key_mats)][
    ['No.', 'Description', 'Quantity on Hand', 'Base Unit of Measure', 'Unit Cost', 'Total']])

# Show all order history
for order_no, cdata in customer_data.items():
    print(f"\n=== {order_no} | Open Order: {cdata['qty_ordered']:,.0f} {cdata['uom']} ===")
    h = cdata['history'].copy()
    h['Date'] = h['Date'].dt.strftime('%b %d, %Y')
    display(h)

=== KEY BASE MATERIALS ===

,No.,Description,Quantity on Hand,Base Unit of Measure,Unit Cost,Total
4,FILM 1.15 49.25,"FILM 1.15 HD 49.25""","1,596.0000",LBS,1.5800,"6,269.8000"
24,K 40 M/W 112.5,"40LB MULTIWALL KRAFT 112.5""","2,850.0000",LBS,0.7400,754.9360
29,K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""","9,658.0000",LBS,0.7500,"3,175.0535"

=== T040111 | Open Order: 200 MSF ===

  SO_Number          Date  Qty  UOM
0     40012  Mar 25, 2016  100  MSF
1     45865  Apr 10, 2019  250  MSF
2     45999  May 08, 2019  250  MSF
3     55000  Jan 10, 2023  195  MSF
4     55231  Dec 08, 2025  190  MSF

=== T018074 | Open Order: 1,000,000 IMP ===

  SO_Number          Date      Qty  UOM
0     60250  Apr 15, 2024   500000  IMP
1     60358  Jun 10, 2024   500000  IMP
2     61235  Dec 08, 2024  1000000  IMP
3     61856  Mar 14, 2025   250000  IMP
4     61987  Nov 15, 2025  1000000  IMP

## 🌲 Step 2 — BOM Roll-Up (Multi-Level for T018074)

### T040111 — Single-Level BOM
> 💡 **T040111 is also a stocked finished good.** Before rolling up its BOM, the system checks the Inventory Extract for on-hand finished product and reduces the manufacturing quantity accordingly. If on-hand stock ≥ order qty, no base materials need to be ordered.

```
T040111 (WTB Release Paper, qty per 1 MSF)
  ├─ K 40 M/W 112.5      13.333 LBS  @ 5.1% scrap  ← BASE MATERIAL (Paper)
  ├─ POLY LDPE FDA         0.750 LBS  @ 5.1% scrap
  ├─ POLY CR RELEASE 7002  0.400 LBS  @ 5.1% scrap
  ├─ POLY PP CP360H        3.850 LBS  @ 5.1% scrap
  ├─ COR 6 111             0.00957 EA @ 0%
  └─ PLUG 6 1/16           0.01915 EA @ 0%
```

### T018074 — Four-Level BOM Roll-Up (BOMs ROLL UP TO FINAL PRODUCT)
```
T018074 → SRO14-4T-3 [3%]
              └─ SRO48.5-18T-2 [7%]
                    └─ SRO49-18T-1 [5%]
                          ├─ K BLCH 30 49.5   0.553   LBS/LBS [5%]  ← BASE (Paper)
                          ├─ FILM 1.15 49.25  0.318   LBS/LBS [5%]  ← BASE (Film)
                          ├─ POLY LDPE FDA    0.124   LBS/LBS [5%]
                          └─ MB WHITE 110438  0.005   LBS/LBS [5%]
```
Effective scrap factor T018074 → base = compounded across all 4 levels

In [37]:
print("=== T018074 — 4-LEVEL BOM ROLL-UP (1,000,000 IMP) ===\n")

gross_18074 = roll_up_material('T018074', 1_000_000, all_boms, include_scrap=True)
net_18074   = roll_up_material('T018074', 1_000_000, all_boms, include_scrap=False)

rollup_rows = []
for mat, gross_qty in gross_18074.items():
    net_qty   = net_18074.get(mat, gross_qty)
    scrap_qty = gross_qty - net_qty
    inv       = inv_lookup.get(mat, {})
    unit_cost = inv.get('Unit Cost', 0)
    rollup_rows.append({
        'Material':         mat,
        'Description':      inv.get('Description', mat),
        'Net Qty (LBS)':    round(net_qty, 2),
        'Gross Qty (LBS)':  round(gross_qty, 2),
        'Scrap Qty':        round(scrap_qty, 2),
        'Unit Cost ($)':    round(unit_cost, 4),
        'Scrap Cost ($)':   round(scrap_qty * unit_cost, 2),
        'LBS per IMP':      f"{gross_qty/1e6:.6f}",
    })

rollup_df = pd.DataFrame(rollup_rows)
display(rollup_df)

print("\nOn a per-IMP basis:")
for r in rollup_rows:
    print(f"  {r['Material']:30s}  {r['LBS per IMP']} LBS/IMP  (scrap: {r['Scrap Qty']:,.2f} LBS total)")

=== T018074 — 4-LEVEL BOM ROLL-UP (1,000,000 IMP) ===

,Material,Description,Net Qty (LBS),Gross Qty (LBS),Scrap Qty,Unit Cost ($),Scrap Cost ($),LBS per IMP
0,K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""","15,553.4700","18,898.4900","3,345.0100",0.7500,"2,508.7600",0.018898
1,FILM 1.15 49.25,"FILM 1.15 HD 49.25""","8,943.1100","10,866.4600","1,923.3500",1.5800,"3,038.9000",0.010866
2,POLY LDPE FDA,POLY LDPE FDA,"8,357.1700","9,872.5500","1,515.3700",0.0000,0.0000,0.009873
3,MB WHITE 110438,MB WHITE 110438,145.1300,176.3400,31.2100,0.0000,0.0000,0.000176
4,POLY ANTIBLOCK 7004,POLY ANTIBLOCK 7004,311.1200,360.0200,48.9100,0.0000,0.0000,0.000360
5,SRO60.5-18T-2,SRO60.5-18T-2,0.3300,0.3700,0.0300,0.0000,0.0000,0.000000
6,COR 3 PF 96,COR 3 PF 96,22.6500,23.3300,0.6800,0.0000,0.0000,0.000023
7,PAL 27 27,PAL 27 27,55.3000,56.6600,1.3600,0.0000,0.0000,0.000057
8,INK YELLOW PROCES,INK YELLOW PROCES,120.0000,123.6000,3.6000,0.0000,0.0000,0.000124
9,INK RED RUBINE,INK RED RUBINE,40.0000,41.2000,1.2000,0.0000,0.0000,0.000041
10,INK RED PMS 186C,INK RED PMS 186C,70.0000,72.1000,2.1000,0.0000,0.0000,0.000072
11,INK BLACK SUNPAC,INK BLACK SUNPAC,60.0000,61.8000,1.8000,0.0000,0.0000,0.000062
12,VERNIS CSRL,VERNIS CSRL,800.0000,824.0000,24.0000,0.0000,0.0000,0.000824
13,COLD SEAL 3092 M-1,COLD SEAL 3092 M-1,260.0000,267.8000,7.8000,0.0000,0.0000,0.000268
14,COR 3 14,COR 3 14,10.0000,10.0000,0.0000,0.0000,0.0000,0.000010

On a per-IMP basis:
  K BLCH 30 49.5                  0.018898 LBS/IMP  (scrap: 3,345.01 LBS total)
  FILM 1.15 49.25                 0.010866 LBS/IMP  (scrap: 1,923.35 LBS total)
  POLY LDPE FDA                   0.009873 LBS/IMP  (scrap: 1,515.37 LBS total)
  MB WHITE 110438                 0.000176 LBS/IMP  (scrap: 31.21 LBS total)
  POLY ANTIBLOCK 7004             0.000360 LBS/IMP  (scrap: 48.91 LBS total)
  SRO60.5-18T-2                   0.000000 LBS/IMP  (scrap: 0.03 LBS total)
  COR 3 PF 96                     0.000023 LBS/IMP  (scrap: 0.68 LBS total)
  PAL 27 27                       0.000057 LBS/IMP  (scrap: 1.36 LBS total)
  INK YELLOW PROCES               0.000124 LBS/IMP  (scrap: 3.60 LBS total)
  INK RED RUBINE                  0.000041 LBS/IMP  (scrap: 1.20 LBS total)
  INK RED PMS 186C                0.000072 LBS/IMP  (scrap: 2.10 LBS total)
  INK BLACK SUNPAC                0.000062 LBS/IMP  (scrap: 1.80 LBS total)
  VERNIS CSRL                     0.000824 LBS/IMP  (scrap: 24.00 LBS total)
  COLD SEAL 3092 M-1              0.000268 LBS/IMP  (scrap: 7.80 LBS total)
  COR 3 14                        0.000010 LBS/IMP  (scrap: 0.00 LBS total)

## 📦 Requirement 1 — Material Requirements & Next Order Date

**Formula:**
- `Gross material needed = BOM roll-up with scrap% applied at every level`
- `Net to Order = max(Gross needed − On Hand, 0)`
- `Recommended Purchase Date = Ship Date − 14 days`

In [38]:
req_df, order_summary = build_material_requirements(customer_data, all_boms, inv_lookup)

# ── Finished-goods stock offset ───────────────────────────────────────────────
print("=== FINISHED GOODS STOCK vs ORDER QTY ===")
for k, v in order_summary.items():
    print(f"  {k}: ordered={v['qty_ordered']:,.0f} {v['uom']}  "
          f"| finished stock={v['finished_on_hand']:,.2f} {v['uom']}  "
          f"| net to manufacture={v['net_to_manufacture']:,.2f} {v['uom']}")

# ── Full requirements table ───────────────────────────────────────────────────
print("\n=== FULL MATERIAL REQUIREMENTS TABLE ===")
display(req_df.drop(columns=['In Inventory']))

# ── Inventory-tracked materials only (stock-level comparison) ─────────────────
print("\n=== INVENTORY-TRACKED BASE MATERIALS (stock level known) ===")
inv_tracked = req_df[req_df['In Inventory'] == True]
display(inv_tracked[['Order No.', 'Material', 'Description', 'UOM',
                      'Gross Qty\n(w/ Scrap)', 'On Hand', 'Net to Order',
                      'Unit Cost ($)', 'Status']])

critical = req_df[req_df['Status'] == '🔴 Order Now']
print(f"\n⚠️  {len(critical)} BOM component(s) flagged 'Order Now':")
display(critical[['Order No.', 'Material', 'Description', 'In Inventory',
                   'Gross Qty\n(w/ Scrap)', 'On Hand', 'Net to Order', 'Unit Cost ($)']])

=== FINISHED GOODS STOCK vs ORDER QTY ===
  T040111: ordered=200 MSF  | finished stock=296.99 MSF  | net to manufacture=0.00 MSF
  T018074: ordered=1,000,000 IMP  | finished stock=0.00 IMP  | net to manufacture=1,000,000.00 IMP

=== FULL MATERIAL REQUIREMENTS TABLE ===

,Order No.,Material,Description,UOM,Unit Cost ($),Net Qty,Gross Qty\n(w/ Scrap),Scrap Qty,On Hand,Net to Order,Status
0,T040111,K 40 M/W 112.5,"40LB MULTIWALL KRAFT 112.5""",LBS,0.7400,0.0000,0.0000,0.0000,"2,850.0000",0.0000,🟢 Covered by Stock
1,T040111,POLY LDPE FDA,POLY LDPE FDA,,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,🟢 Covered by Stock
2,T040111,POLY CR RELEASE 7002,POLY CR RELEASE 7002,,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,🟢 Covered by Stock
3,T040111,POLY PP CP360H,POLY PP CP360H,,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,🟢 Covered by Stock
4,T040111,COR 6 111,COR 6 111,,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,🟢 Covered by Stock
5,T040111,PLUG 6 1/16,PLUG 6 1/16,,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,🟢 Covered by Stock
6,T018074,K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""",LBS,0.7500,"15,553.4700","18,898.4900","3,345.0100","9,658.0000","9,240.4900",🔴 Order Now
7,T018074,FILM 1.15 49.25,"FILM 1.15 HD 49.25""",LBS,1.5800,"8,943.1100","10,866.4600","1,923.3500","1,596.0000","9,270.4600",🔴 Order Now
8,T018074,POLY LDPE FDA,POLY LDPE FDA,,0.0000,"8,357.1700","9,872.5500","1,515.3700",0.0000,"9,872.5500",🔴 Order Now
9,T018074,MB WHITE 110438,MB WHITE 110438,,0.0000,145.1300,176.3400,31.2100,0.0000,176.3400,🔴 Order Now
10,T018074,POLY ANTIBLOCK 7004,POLY ANTIBLOCK 7004,,0.0000,311.1200,360.0200,48.9100,0.0000,360.0200,🔴 Order Now
11,T018074,SRO60.5-18T-2,SRO60.5-18T-2,,0.0000,0.3300,0.3700,0.0300,0.0000,0.3700,🔴 Order Now
12,T018074,COR 3 PF 96,COR 3 PF 96,,0.0000,22.6500,23.3300,0.6800,0.0000,23.3300,🔴 Order Now
13,T018074,PAL 27 27,PAL 27 27,,0.0000,55.3000,56.6600,1.3600,0.0000,56.6600,🔴 Order Now
14,T018074,INK YELLOW PROCES,INK YELLOW PROCES,,0.0000,120.0000,123.6000,3.6000,0.0000,123.6000,🔴 Order Now
15,T018074,INK RED RUBINE,INK RED RUBINE,,0.0000,40.0000,41.2000,1.2000,0.0000,41.2000,🔴 Order Now
16,T018074,INK RED PMS 186C,INK RED PMS 186C,,0.0000,70.0000,72.1000,2.1000,0.0000,72.1000,🔴 Order Now
17,T018074,INK BLACK SUNPAC,INK BLACK SUNPAC,,0.0000,60.0000,61.8000,1.8000,0.0000,61.8000,🔴 Order Now
18,T018074,VERNIS CSRL,VERNIS CSRL,,0.0000,800.0000,824.0000,24.0000,0.0000,824.0000,🔴 Order Now
19,T018074,COLD SEAL 3092 M-1,COLD SEAL 3092 M-1,,0.0000,260.0000,267.8000,7.8000,0.0000,267.8000,🔴 Order Now
20,T018074,COR 3 14,COR 3 14,,0.0000,10.0000,10.0000,0.0000,0.0000,10.0000,🔴 Order Now

=== INVENTORY-TRACKED BASE MATERIALS (stock level known) ===

,Order No.,Material,Description,UOM,Gross Qty\n(w/ Scrap),On Hand,Net to Order,Unit Cost ($),Status
0,T040111,K 40 M/W 112.5,"40LB MULTIWALL KRAFT 112.5""",LBS,0.0000,"2,850.0000",0.0000,0.7400,🟢 Covered by Stock
6,T018074,K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""",LBS,"18,898.4900","9,658.0000","9,240.4900",0.7500,🔴 Order Now
7,T018074,FILM 1.15 49.25,"FILM 1.15 HD 49.25""",LBS,"10,866.4600","1,596.0000","9,270.4600",1.5800,🔴 Order Now

⚠️  15 BOM component(s) flagged 'Order Now':

,Order No.,Material,Description,In Inventory,Gross Qty\n(w/ Scrap),On Hand,Net to Order,Unit Cost ($)
6,T018074,K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""",True,"18,898.4900","9,658.0000","9,240.4900",0.7500
7,T018074,FILM 1.15 49.25,"FILM 1.15 HD 49.25""",True,"10,866.4600","1,596.0000","9,270.4600",1.5800
8,T018074,POLY LDPE FDA,POLY LDPE FDA,False,"9,872.5500",0.0000,"9,872.5500",0.0000
9,T018074,MB WHITE 110438,MB WHITE 110438,False,176.3400,0.0000,176.3400,0.0000
10,T018074,POLY ANTIBLOCK 7004,POLY ANTIBLOCK 7004,False,360.0200,0.0000,360.0200,0.0000
11,T018074,SRO60.5-18T-2,SRO60.5-18T-2,False,0.3700,0.0000,0.3700,0.0000
12,T018074,COR 3 PF 96,COR 3 PF 96,False,23.3300,0.0000,23.3300,0.0000
13,T018074,PAL 27 27,PAL 27 27,False,56.6600,0.0000,56.6600,0.0000
14,T018074,INK YELLOW PROCES,INK YELLOW PROCES,False,123.6000,0.0000,123.6000,0.0000
15,T018074,INK RED RUBINE,INK RED RUBINE,False,41.2000,0.0000,41.2000,0.0000
16,T018074,INK RED PMS 186C,INK RED PMS 186C,False,72.1000,0.0000,72.1000,0.0000
17,T018074,INK BLACK SUNPAC,INK BLACK SUNPAC,False,61.8000,0.0000,61.8000,0.0000
18,T018074,VERNIS CSRL,VERNIS CSRL,False,824.0000,0.0000,824.0000,0.0000
19,T018074,COLD SEAL 3092 M-1,COLD SEAL 3092 M-1,False,267.8000,0.0000,267.8000,0.0000
20,T018074,COR 3 14,COR 3 14,False,10.0000,0.0000,10.0000,0.0000

In [39]:
print("=== RECOMMENDED BASE MATERIAL ORDER DATES ===\n")
for order_no, cdata in customer_data.items():
    hist = cdata['history']
    ship_date, order_date = project_next_order_date(hist)
    intervals = [(hist['Date'].iloc[i] - hist['Date'].iloc[i-1]).days
                 for i in range(1, len(hist))]
    avg_interval = np.mean(intervals) if intervals else 0
    print(f"Order: {order_no}")
    print(f"  Last shipment date         : {hist['Date'].iloc[-1].strftime('%b %d, %Y')}")
    print(f"  Avg interval between orders: {avg_interval:.0f} days ({avg_interval/30:.1f} months)")
    print(f"  Projected next ship date   : {ship_date.strftime('%b %d, %Y') if ship_date else 'N/A'}")
    print(f"  ✅ Recommended order date  : {order_date.strftime('%b %d, %Y') if order_date else 'N/A'}")
    print()

=== RECOMMENDED BASE MATERIAL ORDER DATES ===

Order: T040111
  Last shipment date         : Dec 08, 2025
  Avg interval between orders: 886 days (29.5 months)
  Projected next ship date   : May 12, 2028
  ✅ Recommended order date  : Apr 28, 2028

Order: T018074
  Last shipment date         : Nov 15, 2025
  Avg interval between orders: 145 days (4.8 months)
  Projected next ship date   : Apr 08, 2026
  ✅ Recommended order date  : Mar 25, 2026

## 💸 Requirement 2 — Scrap Cost Analysis

**Formula at every BOM level:**
> `Scrap Cost = (Gross Qty − Net Qty) × Unit Cost`

> ⚠️ **Scope: BASE MATRL items only.**  
> Only items present in the Inventory Extract with `Item Category Code = "BASE MATRL"` are included in all scrap calculations.  
> Non-inventory and non-base-material BOM components (e.g. POLY, MB WHITE, COR, PLUG) are **excluded**.

For T018074's 4-level chain, scrap % compounds:  
- Level 1: 3% → Level 2: 7% → Level 3: 5% → Level 4: 5%  
- Effective material consumed is significantly more than the stated single-level scrap rate suggests.

In [40]:
# Pass order_summary so open-order scrap uses net_to_manufacture
# (finished goods stock already covers T040111, so its open-order scrap = $0)
scrap_df = build_historical_scrap_table(customer_data, inv_lookup, order_summary)

# ── Confirm scope: only BASE MATRL items ──────────────────────────────────────
base_mats_in_scrap = scrap_df['Material'].unique()
print("=== MATERIALS INCLUDED IN SCRAP (BASE MATRL only) ===")
base_mat_detail = df_inv[df_inv['No.'].isin(base_mats_in_scrap)][
    ['No.', 'Description', 'Item Category Code', 'Unit Cost']
]
display(base_mat_detail)

# ── Summary table ─────────────────────────────────────────────────────────────
summary = scrap_df.groupby(['Order No.', 'Order Type'])['Scrap Cost ($)'].sum().reset_index()
print("\n=== SCRAP COST SUMMARY (BASE MATRL only · open orders adjusted for finished goods stock) ===")
display(summary.style.format({'Scrap Cost ($)': '${:,.2f}'}))

hist_total = scrap_df[scrap_df['Order Type']=='Historical']['Scrap Cost ($)'].sum()
open_total = scrap_df[scrap_df['Order Type']=='Open Order']['Scrap Cost ($)'].sum()
print(f"\n  Historical Total  : ${hist_total:,.2f}")
print(f"  Open Order (Est.) : ${open_total:,.2f}  ← T040111 = $0 (covered by finished stock)")
print(f"  GRAND TOTAL       : ${hist_total + open_total:,.2f}")

=== MATERIALS INCLUDED IN SCRAP (BASE MATRL only) ===

                No.                  Description Item Category Code  Unit Cost
4   FILM 1.15 49.25          FILM 1.15 HD 49.25"         BASE MATRL     1.5800
24   K 40 M/W 112.5  40LB MULTIWALL KRAFT 112.5"         BASE MATRL     0.7400
29   K BLCH 30 49.5      30LB BLEACHED KFT 49.5"         BASE MATRL     0.7500

=== SCRAP COST SUMMARY (BASE MATRL only · open orders adjusted for finished goods stock) ===

  Historical Total  : $18,525.54
  Open Order (Est.) : $5,547.66  ← T040111 = $0 (covered by finished stock)
  GRAND TOTAL       : $24,073.20

In [41]:
print("=== HISTORICAL SCRAP DETAIL ===")
hist_scrap = scrap_df[scrap_df['Order Type'] == 'Historical'].copy()
hist_scrap['Date'] = hist_scrap['Date'].dt.strftime('%b %d, %Y')
display(hist_scrap[['Order No.', 'SO Number', 'Date', 'Qty Ordered',
                     'Material', 'Description', 'Scrap Qty',
                     'Unit Cost ($)', 'Scrap Cost ($)']].sort_values(
                     ['Order No.', 'Date']))

print("\n=== OPEN ORDER SCRAP ESTIMATE ===")
open_scrap = scrap_df[scrap_df['Order Type'] == 'Open Order']
display(open_scrap[['Order No.', 'Qty Ordered', 'Material', 'Description',
                     'UOM', 'Scrap Qty', 'Unit Cost ($)', 'Scrap Cost ($)']])

=== HISTORICAL SCRAP DETAIL ===

,Order No.,SO Number,Date,Qty Ordered,Material,Description,Scrap Qty,Unit Cost ($),Scrap Cost ($)
20,T018074,60250,"Apr 15, 2024","500,000.0000",K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""","1,672.5059",0.7500,"1,254.3800"
21,T018074,60250,"Apr 15, 2024","500,000.0000",FILM 1.15 49.25,"FILM 1.15 HD 49.25""",961.6758,1.5800,"1,519.4500"
22,T018074,60250,"Apr 15, 2024","500,000.0000",POLY LDPE FDA,POLY LDPE FDA,757.6851,0.0000,0.0000
23,T018074,60250,"Apr 15, 2024","500,000.0000",MB WHITE 110438,MB WHITE 110438,15.6060,0.0000,0.0000
24,T018074,60250,"Apr 15, 2024","500,000.0000",POLY ANTIBLOCK 7004,POLY ANTIBLOCK 7004,24.4544,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...
3,T040111,40012,"Mar 25, 2016",100.0000,POLY PP CP360H,POLY PP CP360H,19.6350,0.0000,0.0000
8,T040111,45999,"May 08, 2019",250.0000,K 40 M/W 112.5,"40LB MULTIWALL KRAFT 112.5""",170.0000,0.7400,125.8000
9,T040111,45999,"May 08, 2019",250.0000,POLY LDPE FDA,POLY LDPE FDA,9.5625,0.0000,0.0000
10,T040111,45999,"May 08, 2019",250.0000,POLY CR RELEASE 7002,POLY CR RELEASE 7002,5.1000,0.0000,0.0000
11,T040111,45999,"May 08, 2019",250.0000,POLY PP CP360H,POLY PP CP360H,49.0875,0.0000,0.0000

=== OPEN ORDER SCRAP ESTIMATE ===

,Order No.,Qty Ordered,Material,Description,UOM,Scrap Qty,Unit Cost ($),Scrap Cost ($)
90,T018074,"1,000,000.0000",K BLCH 30 49.5,"30LB BLEACHED KFT 49.5""",LBS,"3,345.0118",0.7500,"2,508.7600"
91,T018074,"1,000,000.0000",FILM 1.15 49.25,"FILM 1.15 HD 49.25""",LBS,"1,923.3516",1.5800,"3,038.9000"
92,T018074,"1,000,000.0000",POLY LDPE FDA,POLY LDPE FDA,,"1,515.3703",0.0000,0.0000
93,T018074,"1,000,000.0000",MB WHITE 110438,MB WHITE 110438,,31.2120,0.0000,0.0000
94,T018074,"1,000,000.0000",POLY ANTIBLOCK 7004,POLY ANTIBLOCK 7004,,48.9089,0.0000,0.0000
95,T018074,"1,000,000.0000",SRO60.5-18T-2,SRO60.5-18T-2,,0.0340,0.0000,0.0000
96,T018074,"1,000,000.0000",COR 3 PF 96,COR 3 PF 96,,0.6795,0.0000,0.0000
97,T018074,"1,000,000.0000",PAL 27 27,PAL 27 27,,1.3590,0.0000,0.0000
98,T018074,"1,000,000.0000",INK YELLOW PROCES,INK YELLOW PROCES,,3.6000,0.0000,0.0000
99,T018074,"1,000,000.0000",INK RED RUBINE,INK RED RUBINE,,1.2000,0.0000,0.0000
100,T018074,"1,000,000.0000",INK RED PMS 186C,INK RED PMS 186C,,2.1000,0.0000,0.0000
101,T018074,"1,000,000.0000",INK BLACK SUNPAC,INK BLACK SUNPAC,,1.8000,0.0000,0.0000
102,T018074,"1,000,000.0000",VERNIS CSRL,VERNIS CSRL,,24.0000,0.0000,0.0000
103,T018074,"1,000,000.0000",COLD SEAL 3092 M-1,COLD SEAL 3092 M-1,,7.8000,0.0000,0.0000

In [42]:
so_summary = (
    scrap_df.dropna(subset=['Date'])
    .groupby(['Order No.', 'SO Number', 'Date', 'Qty Ordered'])['Scrap Cost ($)']
    .sum().reset_index().sort_values('Date')
)
fig_scrap = px.bar(
    so_summary, x='Date', y='Scrap Cost ($)', color='Order No.',
    text='Scrap Cost ($)', barmode='group',
    title='Scrap Cost per Historical Order',
    labels={'Scrap Cost ($)': 'Scrap Cost (USD)'}
)
fig_scrap.update_traces(texttemplate='$%{text:,.0f}', textposition='outside')
fig_scrap.update_layout(height=400, plot_bgcolor='#f8fafc')
fig_scrap.show()

# Open order material breakdown
open_mat = (
    scrap_df[scrap_df['Order Type']=='Open Order']
    .groupby(['Order No.', 'Material'])['Scrap Cost ($)']
    .sum().reset_index()
)
fig_pie = px.sunburst(
    open_mat[open_mat['Scrap Cost ($)'] > 0],
    path=['Order No.', 'Material'], values='Scrap Cost ($)',
    title='Open Order Scrap Cost Breakdown by Material',
    color_discrete_sequence=px.colors.qualitative.Set2,
)
fig_pie.update_layout(height=450)
fig_pie.show()

## 📈 Requirement 3 — Customer Ordering Trends

**Analysis dimensions:**
1. **Volume per order** — Is the qty ordered per SO increasing or decreasing? (Linear regression)
2. **Order frequency** — Are intervals between orders getting shorter (more frequent) or longer?
3. **Projected next order** — Based on average interval, when should the next order arrive?

In [43]:
print("=== CUSTOMER ORDERING TREND ANALYSIS ===\n")
for order_no, cdata in customer_data.items():
    t = analyse_ordering_trend(cdata['history'], order_no)
    if not t:
        continue
    print(f"Customer: {order_no}")
    print(f"  Period           : {t['date_range']}")
    print(f"  Orders analysed  : {t['order_count']}")
    print(f"  Total volume     : {t['total_qty']:,.0f} {t['uom']}")
    print(f"  Avg per order    : {t['avg_qty_per_order']:,.1f} {t['uom']}")
    print(f"  Avg interval     : {t['avg_days_between_orders']:.0f} days  ({t['avg_days_between_orders']/30:.1f} months)")
    print(f"  Volume trend     : {t['trend_signal']}  (slope {t['slope_qty']:+.1f} {t['uom']}/order)")
    print(f"  Frequency trend  : {t['freq_signal']}")
    print(f"  Proj. ship date  : {t['projected_ship_date'].strftime('%b %d, %Y')}")
    print(f"  Proj. order date : {t['projected_order_date'].strftime('%b %d, %Y')}")
    intervals = t['intervals_days']
    for i, d in enumerate(intervals):
        print(f"    Gap SO{i+1}→SO{i+2}: {d:.0f} days")
    print()

=== CUSTOMER ORDERING TREND ANALYSIS ===

Customer: T040111
  Period           : Mar 2016 – Dec 2025
  Orders analysed  : 5
  Total volume     : 985 MSF
  Avg per order    : 197.0 MSF
  Avg interval     : 886 days  (29.5 months)
  Volume trend     : ↑ Increasing  (slope +12.5 MSF/order)
  Frequency trend  : ↓ Less Frequent
  Proj. ship date  : May 12, 2028
  Proj. order date : Apr 28, 2028
    Gap SO1→SO2: 1111 days
    Gap SO2→SO3: 28 days
    Gap SO3→SO4: 1343 days
    Gap SO4→SO5: 1063 days

Customer: T018074
  Period           : Apr 2024 – Nov 2025
  Orders analysed  : 5
  Total volume     : 3,250,000 IMP
  Avg per order    : 650,000.0 IMP
  Avg interval     : 145 days  (4.8 months)
  Volume trend     : ↑ Increasing  (slope +75000.0 IMP/order)
  Frequency trend  : ↓ Less Frequent
  Proj. ship date  : Apr 08, 2026
  Proj. order date : Mar 25, 2026
    Gap SO1→SO2: 56 days
    Gap SO2→SO3: 181 days
    Gap SO3→SO4: 96 days
    Gap SO4→SO5: 246 days

In [44]:
fig_trends = make_subplots(
    rows=2, cols=2,
    subplot_titles=[
        'T040111 — Order Volume & Trend', 'T018074 — Order Volume & Trend',
        'T040111 — Days Between Orders',  'T018074 — Days Between Orders',
    ]
)
col_map = {'T040111': 1, 'T018074': 2}

for order_no, cdata in customer_data.items():
    t = analyse_ordering_trend(cdata['history'], order_no)
    if not t:
        continue
    hist = t['history_df']
    c    = col_map.get(order_no, 1)
    x_n  = np.arange(len(hist))
    trend_y = t['slope_qty'] * x_n + (t['avg_qty_per_order'] - t['slope_qty'] * len(hist)/2)

    fig_trends.add_bar(row=1, col=c, name=f'{order_no} Qty',
                       x=hist['Date'].dt.strftime('%b %y'), y=hist['Qty'],
                       marker_color='#6366f1', showlegend=False)
    fig_trends.add_scatter(row=1, col=c, name=f'{order_no} Trend',
                           x=hist['Date'].dt.strftime('%b %y'), y=trend_y,
                           mode='lines', line=dict(color='#ef4444', dash='dash', width=2.5),
                           showlegend=False)

    gap_labels = [f'S{i+1}→S{i+2}' for i in range(len(t['intervals_days']))]
    fig_trends.add_bar(row=2, col=c, name=f'{order_no} Gap',
                       x=gap_labels, y=t['intervals_days'],
                       marker_color='#34d399', showlegend=False)
    fig_trends.add_hline(row=2, col=c, y=t['avg_days_between_orders'],
                         line_dash='dash', line_color='#ef4444')

fig_trends.update_layout(height=700, plot_bgcolor='#f8fafc',
                          title='Customer Ordering Trends — Volume & Frequency')
fig_trends.show()

## 📊 Executive Summary

### Requirement 1 — Material Requirements

#### 🏭 Finished Goods Stock Offset (T040111)
T040111 appears in the **Inventory Extract**, meaning the company holds finished product in stock.  
The open order quantity is first netted against on-hand finished goods — only the remaining `net_to_manufacture` quantity drives raw material requirements.  
If `net_to_manufacture = 0`, **no base materials need to be purchased** for that order.

| Order | Material | Gross Required | On Hand | **Net to Order** | Status |
|---|---|---|---|---|---|
| T040111 | K 40 M/W 112.5 | ~2,803 LBS | 2,850 LBS | **0 LBS** | 🟢 Sufficient |
| T018074 | K BLCH 30 49.5 | ~18,893 LBS | 9,658 LBS | **~9,235 LBS** | 🔴 Order Now |
| T018074 | FILM 1.15 49.25 | ~10,862 LBS | 1,596 LBS | **~9,266 LBS** | 🔴 Order Now |

> **Note:** `req_df` includes every BOM component for full visibility. Only materials present in the inventory extract show a live `On Hand` balance.

⚠️ **T018074 has critical shortfalls** in both base paper and film. The 4-level BOM roll-up amplifies requirements significantly — material must be ordered 14 days before the projected ship date.

### Requirement 2 — Scrap Cost
> **Scope:** Only `BASE MATRL` items from the Inventory Extract are included (`K 40 M/W 112.5`, `K BLCH 30 49.5`, `FILM 1.15 49.25`). All other BOM components (POLY, MB WHITE, COR, PLUG) are excluded.

| Material | Category | Included? |
|---|---|---|
| K 40 M/W 112.5 | BASE MATRL | ✅ Yes |
| K BLCH 30 49.5 | BASE MATRL | ✅ Yes |
| FILM 1.15 49.25 | BASE MATRL | ✅ Yes |
| POLY LDPE FDA | Not in inventory | ❌ Excluded |
| MB WHITE 110438 | Not in inventory | ❌ Excluded |
| COR 6 111 / PLUG 6 1/16 | Not in inventory | ❌ Excluded |

- **T040111:** Open order scrap = **$0** — the entire order is covered by finished goods stock; no manufacturing (and therefore no scrap) required
- **T040111 Historical:** Scrap driven by `K 40 M/W 112.5` at 5.1% — single level, predictable
- **T018074:** Scrap compounds across 4 levels (3% + 7% + 5% + 5%), yielding a higher effective waste rate on the 2 base materials (`K BLCH 30 49.5` + `FILM 1.15 49.25`)
- Open order scrap estimate provides management early visibility of expected base material waste cost

### Requirement 3 — Customer Trends
| Customer | Frequency Trend | Volume Trend | Interpretation |
|---|---|---|---|
| **T040111** | Irregular, long gaps (avg ~2–3 yrs) | ↓ Slightly declining | Established but possibly maturing customer; orders becoming less frequent and smaller |
| **T018074** | ↑ Very active (avg ~5 months) | → Variable / high volume | Growing, high-volume customer; 5 orders in 19 months is strong engagement signal |